version: 0.0
os: linux
files:
  - source: /
    destination: /app/pubg_bot
permissions:
  - object: /app/pubg_bot
    owner: ec2-user
    group: ec2-user
    mode: 744
hooks:
  AfterInstall:
    - location: code-deploy-scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: code-deploy-scripts/start_server.sh
      timeout: 300
      runas: ec2-user
