version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/apps/pubg_bot
hooks:
  AfterInstall:
    - location: code-deploy-scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: code-deploy-scripts/start_server.sh
      timeout: 300
      runas: ec2-user
